minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade

update:
  ignoreDeps:
    - typescript@7

shellEmulator: true

overrides:
  # check https://npmx.dev/package/why-is-node-running => possible package takeover
  why-is-node-running: 3.2.1

allowBuilds:
  esbuild: true
