/**
 * Generated by tsnapi — public API snapshot of `package-manager-detector/commands`
 */
// #region Functions
export declare function constructCommand(_: AgentCommandValue, _: string[]): ResolvedCommand | null;
export declare function resolveCommand(_: Agent, _: Command, _: string[]): ResolvedCommand | null;
export declare function splitRunArgs(_: string[], _?: string[]): {
    before: string[];
    script: string | undefined;
    after: string[];
};
// #endregion

// #region Variables
export declare const COMMANDS: {
    npm: AgentCommands;
    yarn: AgentCommands;
    'yarn@berry': AgentCommands;
    pnpm: AgentCommands;
    'pnpm@6': AgentCommands;
    'pnpm-rush': AgentCommands;
    bun: AgentCommands;
    aube: AgentCommands;
    deno: AgentCommands;
    nub: AgentCommands;
};
// #endregion