/**
 * Generated by tsnapi — public API snapshot of `package-manager-detector/constants`
 */
// #region Variables
export declare const AGENTS: Agent[];
export declare const INSTALL_METADATA: Record<string, AgentName>;
export declare const INSTALL_PAGE: Record<Agent, string>;
export declare const LOCKS: Record<string, AgentName>;
// #endregion