/**
 * Generated by tsnapi — public API snapshot of `package-manager-detector/detect`
 */
// #region Functions
export declare function detect(_?: DetectOptions): Promise<DetectResult | null>;
export declare function getUserAgent(): AgentName | null;
export declare function normalizeAgentVersion(_: string | undefined): string | undefined;
export declare function resolveAgent(_: AgentName, _?: string): {
    name: AgentName;
    agent: Agent;
    version: string | undefined;
} | undefined;
// #endregion