/**
 * Generated by tsnapi — public API snapshot of `package-manager-detector/detect`
 */
// #region Functions
export declare function detect(_?: DetectOptions): Promise<DetectResult | null>;
export declare function getUserAgent(): AgentName | null;
// #endregion